version: "3.9"

name: anti_messenger

services:
  nginx:
    image: nginx:1.25
    container_name: am_nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./src/static:/usr/share/nginx/html/static:ro
      - ./src/media:/usr/share/nginx/html/media:ro
    ports:
      - 80:80
    restart: unless-stopped
    depends_on:
      api:
        condition: service_healthy

  api:
    build: .
    container_name: am_api
    env_file:
      - .env
    environment:
      - DEBUG=off
      - DB_HOST=database
    restart: unless-stopped
    volumes:
      - ./src:/opt/anti_messenger
    depends_on:
      database:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:8000/"]
      interval: 10s
      timeout: 5s
      retries: 30

  database:
    image: mysql:8.0-debian
    container_name: am_database
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      # MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      TZ: "Europe/Moscow"
    command: >
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    ports:
      - 3306:3306
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root --password=$$DB_PASS"]
      interval: 5s
      timeout: 3s
      retries: 10


networks:
  default:
    name: am_network

volumes:
  db_data:
    name: am_db_data
